ALTER TABLE cards CHANGE card_id card_id INT NOT NULL;
ALTER TABLE cards DROP PRIMARY KEY;
ALTER TABLE cards CHANGE card_id id INT NOT NULL;
ALTER TABLE cards ADD PRIMARY KEY (id);
ALTER TABLE cards ADD COLUMN card_id VARCHAR(255);
