spring:
  datasource:
    url: #
    password: #
    username: #
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  flyway:
    url: ${spring.datasource.url}
    locations: classpath:db/migration
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    enabled: true

jwt:
  token:
    secret: 4125442A472D4B6150645367566B59703373367639792442264528482B4D6251
    expired: 259200000 # 3 * 24 * 60 * 60 * 1000

logging:
  level:
    root: INFO
    com.motrechko.clientconnect: DEBUG
mqtt:
  broker:
    url: #.s2.eu.hivemq.cloud
  port: #
  username: #
  password: #
